### ISSUE TITLE
Correção do Readme

### ISSUE THREAD

**Issue by fabriciosiqp** [teteusAraujo/teteusAraujo#1]
Olá Matheus existe um pequeno erro no seu readme.

 👨‍💻 ~~Estagiaro de Enhenharia de Software na Itaú Unibanco.~~
  👨‍💻 Estagiário de Engenharia de Software na Itaú Unibanco.
  
  Abç.

**Comment by teteusAraujo** [comment]
Muito obrigado @fabriciosiqp !!!! Rsrsrs o pior que eu também já tinha notado o erro só estava esperando eu fazer mais alterações no Readme para da um novo commit ... Mais de qualquer forma, muito obrigado!
